modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="alstakka"
version="${file.jarVersion}"
displayName="Alstakka"
logoFile="alstakka.png"
credits="Thanks to Cy4 and Kaupenjoe for their respective tutorials!"
authors="Probleyes#0794, elizzie#1865, Monka#8008"
description='''
This mod adds the Alstakka! A new tameable mount.
'''
[[dependencies.alstakka]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alstakka]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"